"""add_multi_project_columns

Revision ID: 3a04f8e5a855
Revises: 5853fbdcc7a3
Create Date: 2026-07-01 16:18:37.660112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a04f8e5a855'
down_revision: Union[str, Sequence[str], None] = '5853fbdcc7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('nomba_sub_account_id', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('api_key_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'plans', 'api_keys', ['api_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_column('plans', 'api_key_id')
    op.drop_column('api_keys', 'nomba_sub_account_id')
    # ### end Alembic commands ###
