"""Add cancel_at_period_end

Revision ID: 3f70833ccebb
Revises: 8795a76d49a1
Create Date: 2026-07-02 14:36:14.597707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f70833ccebb'
down_revision: Union[str, Sequence[str], None] = '8795a76d49a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_api_keys_project'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('fk_events_project'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('fk_payments_project'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('fk_plans_project'), 'plans', type_='foreignkey')
    op.create_foreign_key(None, 'plans', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('projects_merchant_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'merchants', ['merchant_id'], ['id'])
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('fk_subscriptions_project'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_project'), 'subscriptions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_merchant_id_fkey'), 'projects', 'merchants', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_plans_project'), 'plans', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_project'), 'payments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_project'), 'events', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('fk_api_keys_project'), 'api_keys', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
