"""increase_key_prefix_length

Revision ID: 5853fbdcc7a3
Revises: f9b4bc5cac0b
Create Date: 2026-07-01 15:45:57.697706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5853fbdcc7a3'
down_revision: Union[str, Sequence[str], None] = 'f9b4bc5cac0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
