"""add_card_brand_and_last4_to_subscriptions

Revision ID: ebfcfeebc406
Revises: 1dd0c6d805da
Create Date: 2026-07-07 20:13:55.414321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfcfeebc406'
down_revision: Union[str, Sequence[str], None] = '1dd0c6d805da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('card_brand', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('card_last4', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'card_last4')
    op.drop_column('subscriptions', 'card_brand')
    # ### end Alembic commands ###
